### PR TITLE
First try to generate files using the generator

### PR DESCRIPTION
**Pull request by koppor**
This switches from CircleCI to GitHub actions. Furthermore, it uses the latex-template-generator.

Open points

- [ ] Generate GitHub pages. See https://github.com/koppor/plantuml/blob/d87bbc868812160f8f95122398294625bb637022/.github/workflows/build-and-publish.yml#L52 for an example

### CODE REVIEW

**Comment by koppor** [comment]
The commit should be done by the action-user:

grafik

**Comment by koppor** [comment]
Note we switched from crazy-max/ghaction-github-pages@v1 to peaceiris/actions-gh-pages@v3 which also works great.

**Comment by k4rtik** [comment]
Is paper.tex supposed to be deleted? If so, what is the default target for the makefile?

**Comment by koppor** [comment]
@k4rtik I did not fully update `README.md`. You have to choose one of the `paper-...tex` files. See the diff at https://github.com/latextemplates/LNCS/commit/f7cd65cc73b46a3428d068e6e198085b8873229b

It was very difficult for me to a) have this repository generated by the [latex-template-generator](https://github.com/latextemplates/generator-latex-template) and b) have the repository itself working.

Maybe, I should generate a `paper.tex` based on the most common default (pdflatex, bibtex, English, listings). Will do that in a follow-up.

Meanwhile, I would recommend to use the latex template generator directly (if it is possible for you to have nodejs installed on your machine).

**Comment by koppor** [comment]
@k4rtik The issue was more complicated. Should be finally fixed by https://github.com/latextemplates/LNCS/pull/33 (which is merged into `main` now).

**Pull request merged**
